### PR TITLE
Splits out individual programs to GitHub Riemann org

### PR DESCRIPTION
**Pull request by jamtur01**
This series of commits:

1. Moves each Riemann binary program to a new repo under the [GitHub Riemann org](https://github.com/riemann/). 

2. Rewrites documentation to reflect this.

3. Cleans up Rakefile and associated to reflect this.

Currently none of the extracted programs have been pushed as gems so this is mostly an "on paper" exercise. When they are all pushed as Gems then we'll need to increment the version on this gem, add some warning text and re-push.

### CODE REVIEW

**Comment by fborgnia** [comment]
I like this, though not 100% sure on splitting out those binaries that only require riemann-tools IE: riemann-health, -fd, -diskstats, -net...

**Comment by jamtur01** [comment]
@fborgnia I considered that and then decided that either Riemann-tools was a framework/scaffold or it wasn't - if that makes sense?

**Comment by fborgnia** [comment]
both the repo and gem name suggests to me a set of basic tools, not only scaffolding, besides that i dont see any benefit from splitting those execs that don't require anything else.

**Comment by jamtur01** [comment]
I guess I think it's confusing. Some of the tools are in one gem and a bunch are not. Feels like a mixed signal. If most folks are managing this with configuration management this allows then to be explicit and granular.

**Comment by jamtur01** [comment]
After discussions with @aphyr we're going to wind some of this back - new rule of thumb - broadly tools with dependencies are separate and others are in the riemann-tools gem.

**Comment by jamtur01** [comment]
I've updated the branch to only remove those with dependencies.

**Pull request merged**
